apiVersion: v1
kind: Secret
metadata:
    name: docmost-secrets
    namespace: docmost
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ehxbhgeI0A==,iv:bL52yi1BoCzfl4WiVSJNZtOHkb+2NyDXWqBp+gFE7B8=,tag:3xEXEqawTVmjujkYhr0lpw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:U8J2uXKFmEKZJx77zJojaS6sx5zcesrodHJKQ88AldA=,iv:pzIVFApKwZkCGc9WhF9DrBiERkLkE5jJphw7v4Q6uFM=,tag:qsZ5gWgcYEV6cqGEbYx4rg==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:ZcguXDJuZp7qDRB4QOmbNhwAfkhawxd/hii5RiolxCVXSpZRL1UCAY+F4N5coj2Mm3dMyhdpTcwXbtkt12RIEg==,iv:sYmCzztJvuS/PLzDjyiEfXwXejDFc2teYu/dLRCLOv8=,tag:yRypKKR/7cTQZk/CmRC+Jw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:mnV01qHg8OEPW/xNhqq0Y98jlMkIC+cvHGGe723x+NsA0LseCmXhxDEPB1wDESvGr6RnffkQqsogGQLt5HqBrFX/CpsHr6hqfIT0vDEtu6AGpVWU58EFDzI=,iv:dMmqw85yD7CC8TwrztlOnbASsTYKMkh4jWrXR883eq8=,tag:CQr7UqulkznnsqxwjKGzog==,type:str]
    TUNNEL_CREDENTIALS: ENC[AES256_GCM,data:2m0+09UTlRza7Ovxn9jvhELv3DG8p4aHZSxfFro/3E4Pewqq+xN+QkVEJfj517Rmm0ljrTxdTltZC9hu9bgQDl6cp3Q3ufGnZ6CuIM1WdDCJSuE959uda28m40zBFBRmtTc3T6Fe2gBHHyJMU94pRw3n78WDPkBluE13AHEMNU9QtGsbkeWMQVg2G/TI/Pj9ZVGl1T0jgi91z+VzywQsEQo84+KHLIcqw7pCT1B5E2u0CTre0ooa6y22RBy4CIA=,iv:O2xgQv2Wc9vreMOAOYVhiLM/Kehru+nXYpuwtE2irhg=,tag:Q8NEXGXcMVNfMPv4TUJoOA==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYkNlOG41czlmcndPbVdR
            azcvNXZlMDBqaEw0V2Y4UjZ1N1VmOWlyT1VJCjdXc2FQSTBrTjVBWG40RENRdExB
            NnlvOG15OTdmNVZQYk5JRHNobUpLMFUKLS0tIFhkandJOWJHN3VVLy9yN25FcE0v
            eUpVUXpjK09OcGFORkVJVFVEOHR2K3cKcpu05I9dX5QTD5r/lxvO63jQqJdO4TS/
            KMzcL+KnwNJVboqDIhlIf7U25VUZm2lRepfpHaIkZiZHE8pPjAVR0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T01:34:20Z"
    mac: ENC[AES256_GCM,data:xyi9+5gjslaqoQJuFu3lYJlyrn959AyjAUWl66rL5Itu/556YDbR+YiEM7F5/NAq3oiH4M9nqJK9pK/VH0+dvdfXY39Mt8Lv9Yz/VhEXd8nZdIx3Kdawc1ys0j2rO1VXbetoV0Q8TEOW1yMbi1dw7gQpSI9f3hloksd2tGW3oYg=,iv:2b8AaEy0ylVgkTTiZmtdVyQ6m2orzjDKPF2Iv3qEYfk=,tag:Kt62M0jxtLQbZMOj3USf+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
