apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
data:
  VIKUNJA_DATABASE_TYPE: "postgres"
  VIKUNJA_DATABASE_HOST: "postgres:5432"
  VIKUNJA_DATABASE_DATABASE: "vikunja"
  VIKUNJA_SERVICE_ENABLEREGISTRATION: "true"
  VIKUNJA_LOG_LEVEL: "info"
  VIKUNJA_MAILER_ENABLED: "false"
  VIKUNJA_DATABASE_MAXOPENCONNECTIONS: "10"
  VIKUNJA_DATABASE_MAXIDLECONNECTIONS: "5"
  VIKUNJA_SERVICE_PUBLICURL: "https://vikunja.deleontech.net"

