apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/falco
# patches:
#   - target:
#       kind: ConfigMap
#       name: falco-config
#     patch: |-
#       - op: replace
#         path: /data/falco.yaml
#         value: |
#           ... environment-specific config ...
