apiVersion: v1
data:
    password: ENC[AES256_GCM,data:H/LHFrUVVsIsWry2,iv:e8OPNx8cey5SmzSarfPZK58h3cKj8VK8oqEwj6qcaiA=,tag:PDnF8sVsqtkpYjEon/+OXw==,type:str]
    user: ENC[AES256_GCM,data:3lkgEjz+oaI=,iv:DUV8fkcx/d1ByZWmmsWsHfGYsOmrpaoXgQ9NtcuCZHA=,tag:MSRoLDKXkEuYdXM6go74mQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmKzdrbFdWSnNYekxqTCti
            MFcwY0RTNk5VTUNqcHlRYXlHSG9EQUErRDFrCk9aRlUzYVZKVlZ1ajFTZUIzRW9Y
            bzBsUnY1RHIxazE2ZXhCU0tHRnB2dlEKLS0tIFJKWkRUOVRhRGh3ZTUwRm5LSWRV
            T2xPaEpObU9iMk5rZ0QxRFJtUzhWMFkKgSwDqq/nfMgbvDQNTVKhQhNoGmloQB/w
            DdLR2sPjZXajXOhdqzkQeYC+IL+ZSM80NNXTOqXg/7bJjgQ4bWT+oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T04:46:10Z"
    mac: ENC[AES256_GCM,data:+2MufkGtdi6+tDQ0Q6EZoXG7T7DZQ6dkP292z8F4yLNJpSf98JnBsvsz7zAHQt3WFVeQ71P7W2JdnyLJKlaq0jk285pOJLrxs7JTmVAFYlZwmAV4VvBxaCAws6h+wwgfCDhKY4Fg/XpwoOeyYYxVlTDM12hagRu/5uaLdke8a5Q=,iv:3wVs0zo7D/PQieiaw1tgtWWalqMfvG0kKNfGyJmAr1Y=,tag:iXbAsnPRO0V6bOSj2oHnrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
