apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-secret
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:988x7j7N+w==,iv:L0S9CZUtrherg8UxoRS0UsgcA0heuAu7Hk4CCyPcaIg=,tag:piS9rAf8G1mEyZe9G80ByQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:UCO4OqHp2Q==,iv:vVZodj/IRgLk7YwkSEvZYgm5u2TJqljbpfvoA67/dUI=,tag:gzDImUea8GrOjaXGIscdMQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:xyE4WadDa9cwZKwYG8Hc5FsM8hO0wg==,iv:0znFIO8FcyHs4HM4Vwvd9LhE/tnoAiET4aGaiOG61yw=,tag:wii9+IOnUXbCLAUTaPhLHQ==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OW1rbHNyVWwwajdDM2o5
            OFdWU2RrbEdUVmpyaFdjTnV6M0FteDZ4NW1VCjl6eXBkTW14NFlUSDlNaDY3YzRr
            UFN1bDhGQVM1QWxmV1BxdVBjemh4SzQKLS0tIEFsMTYrZlNEY3RZeUszdmYxUzZE
            Wk5Tc0gwOXBrcEhHcE1zRExua2tWVUEKvKHcds4IIPAesP0g/gHlpMGTq39xWWGP
            R1xYS8bTPNsT7OI+gygjTQL+azuPlOzES1kpdEOqraIEirtGi5GuBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T04:08:34Z"
    mac: ENC[AES256_GCM,data:MI01DPjbOk1URY+i+1yQG4j7hXkMCdY7Pc1Lfy1bhlxO2byXVL26W3qFG2Y2D5/HBIl4m7UBehLcUv0Kzwhk/nob9kCI/r09q+SgYp0+14QhdFBkAU9jumY3cu8aoheOHtAHx/bKYA4BVZ4M1zH4u2MzeXmM+F1wtdf5rfPfbN4=,iv:REBNQSo6HBOvQXLNKOOPdatLlN2EMCrZSwYL/8ZxLyw=,tag:CZRz2NdheA6BEHQ9FQV7hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
type: Opaque
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:2U6m/cxL4AkXZoBXVPSCE1czxyGO8OQ4KleolXyQSSc=,iv:EBAun0W9Xj0p4ADBhIjT73hPGCPBH4l0PoS2291sBZY=,tag:f57ddwFFuHHRbdLxLZPJfQ==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OW1rbHNyVWwwajdDM2o5
            OFdWU2RrbEdUVmpyaFdjTnV6M0FteDZ4NW1VCjl6eXBkTW14NFlUSDlNaDY3YzRr
            UFN1bDhGQVM1QWxmV1BxdVBjemh4SzQKLS0tIEFsMTYrZlNEY3RZeUszdmYxUzZE
            Wk5Tc0gwOXBrcEhHcE1zRExua2tWVUEKvKHcds4IIPAesP0g/gHlpMGTq39xWWGP
            R1xYS8bTPNsT7OI+gygjTQL+azuPlOzES1kpdEOqraIEirtGi5GuBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T04:08:34Z"
    mac: ENC[AES256_GCM,data:MI01DPjbOk1URY+i+1yQG4j7hXkMCdY7Pc1Lfy1bhlxO2byXVL26W3qFG2Y2D5/HBIl4m7UBehLcUv0Kzwhk/nob9kCI/r09q+SgYp0+14QhdFBkAU9jumY3cu8aoheOHtAHx/bKYA4BVZ4M1zH4u2MzeXmM+F1wtdf5rfPfbN4=,iv:REBNQSo6HBOvQXLNKOOPdatLlN2EMCrZSwYL/8ZxLyw=,tag:CZRz2NdheA6BEHQ9FQV7hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:dGAaQx0Vznv3cQ79N3LhAnOvwpBiLBs7eoKkDdvEl1756xA=,iv:QX+gRYwN80rUetOmoDeZnbcZVR9x+QUG/NeuGBT7uUI=,tag:DCFovkWr9CSj7ZS44T9kLg==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OW1rbHNyVWwwajdDM2o5
            OFdWU2RrbEdUVmpyaFdjTnV6M0FteDZ4NW1VCjl6eXBkTW14NFlUSDlNaDY3YzRr
            UFN1bDhGQVM1QWxmV1BxdVBjemh4SzQKLS0tIEFsMTYrZlNEY3RZeUszdmYxUzZE
            Wk5Tc0gwOXBrcEhHcE1zRExua2tWVUEKvKHcds4IIPAesP0g/gHlpMGTq39xWWGP
            R1xYS8bTPNsT7OI+gygjTQL+azuPlOzES1kpdEOqraIEirtGi5GuBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T04:08:34Z"
    mac: ENC[AES256_GCM,data:MI01DPjbOk1URY+i+1yQG4j7hXkMCdY7Pc1Lfy1bhlxO2byXVL26W3qFG2Y2D5/HBIl4m7UBehLcUv0Kzwhk/nob9kCI/r09q+SgYp0+14QhdFBkAU9jumY3cu8aoheOHtAHx/bKYA4BVZ4M1zH4u2MzeXmM+F1wtdf5rfPfbN4=,iv:REBNQSo6HBOvQXLNKOOPdatLlN2EMCrZSwYL/8ZxLyw=,tag:CZRz2NdheA6BEHQ9FQV7hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
