apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-secret
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:mu7SU+rGcA==,iv:vQTMYNMIvGlwKd9w3MGVqL1qDpXqmArRbwsvrYGGcWg=,tag:2t+BUO+cbxc7NFpQO8rqzg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:QcOPzFFW1Q==,iv:7OdyQHaxSo5QOIO5hRYPlkw0XZ0PcokL2qLVNHxQRmg=,tag:8JdYbrWqN/8J6fCrwKDCLA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AXlAnb10HKUIV1UQ5DFtK5navKlwXg==,iv:sL2+MIF4biNz407Qu5KiDEIVzMLHdAmEGaGH9yMNxVs=,tag:eNH4N/8dgImmXehn71Qq0A==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaUVuWFdGU0dxc3U4TGRM
            Z3M5SGR6Rm80MDh4dnF2SzlCSkZBT1MyYWowClo0UWxQcjVnZlJ5dDJDUkZleGQv
            QStPVEpLZVBEWkQ5cEZ0Y0txSThyQk0KLS0tIEs1NVFUaDVyWjhTTHYrcmtzd0FE
            UHgxR2dPbUEwQ3R0TTBOdk90amUxeWsKjl25keHoO9dE5ac5jNLInlaaOJbrEQyD
            JKIdguLAbdFc/cYsLqGQg5rt7SuvVpsFJAtbmEv0Mguc90zN6qxVpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T05:15:04Z"
    mac: ENC[AES256_GCM,data:eB3/PbL6X7V6Qa9jl/CXp8halnJKIzitgDWwCsijze3Wq6fIJgx7W/OAyXR3ZZzSuz48pQRQ+R67mKqs49nGfWcT7orL5MLbbCnhI634WE/XnT9oZaEGu/y6AJ43CPBO0q8M5ILoIM0IcA3LLDcds2LXJSAsg+MytoHWzAXLrwA=,iv:E/1Ewf9gE3BePl7ApW+ziyNW4rbBoFFJMDXioPq7PJ0=,tag:A/BeK22/9Zddp9TaV9oixg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
type: Opaque
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:JJRsEtLpmHNQTj3z3z9uYmaFltY2yJizFpcyNdaFCmU=,iv:Fg661IlaskNgxuX72Y6hnF1qjnAsZMAu2wDFRb5tpyc=,tag:VkaRAtMAaB3RNpj3C6J5KA==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaUVuWFdGU0dxc3U4TGRM
            Z3M5SGR6Rm80MDh4dnF2SzlCSkZBT1MyYWowClo0UWxQcjVnZlJ5dDJDUkZleGQv
            QStPVEpLZVBEWkQ5cEZ0Y0txSThyQk0KLS0tIEs1NVFUaDVyWjhTTHYrcmtzd0FE
            UHgxR2dPbUEwQ3R0TTBOdk90amUxeWsKjl25keHoO9dE5ac5jNLInlaaOJbrEQyD
            JKIdguLAbdFc/cYsLqGQg5rt7SuvVpsFJAtbmEv0Mguc90zN6qxVpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T05:15:04Z"
    mac: ENC[AES256_GCM,data:eB3/PbL6X7V6Qa9jl/CXp8halnJKIzitgDWwCsijze3Wq6fIJgx7W/OAyXR3ZZzSuz48pQRQ+R67mKqs49nGfWcT7orL5MLbbCnhI634WE/XnT9oZaEGu/y6AJ43CPBO0q8M5ILoIM0IcA3LLDcds2LXJSAsg+MytoHWzAXLrwA=,iv:E/1Ewf9gE3BePl7ApW+ziyNW4rbBoFFJMDXioPq7PJ0=,tag:A/BeK22/9Zddp9TaV9oixg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:QIaZKmkN8wZ0hAxm2HWCZMhzszmiBvjjoSyTYf0buTZgEkLvghJ7SEl4LBy+tLVmK9VfHebzKXCe0Tk9mtgjMDWV+9gIo/fKe8bXwiKvqv4xcMtVAx+IR0pSh4Zt6ulK6vp08Qwxgd+oZuEVzNXd2uTzD+p/bJRsgKGS2UzKUIprY3Qdbi38O8xLk/+SfjQX8dIdLbWEuIE9igEsoriPhEWwnwCoRlNrPXLU2gOwvm0=,iv:UlHBfpD+BEXfmNqhZuArux2hftz9tVGSDkCs243gqow=,tag:itI0Q8H2Equ2JgD7gGMjfg==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaUVuWFdGU0dxc3U4TGRM
            Z3M5SGR6Rm80MDh4dnF2SzlCSkZBT1MyYWowClo0UWxQcjVnZlJ5dDJDUkZleGQv
            QStPVEpLZVBEWkQ5cEZ0Y0txSThyQk0KLS0tIEs1NVFUaDVyWjhTTHYrcmtzd0FE
            UHgxR2dPbUEwQ3R0TTBOdk90amUxeWsKjl25keHoO9dE5ac5jNLInlaaOJbrEQyD
            JKIdguLAbdFc/cYsLqGQg5rt7SuvVpsFJAtbmEv0Mguc90zN6qxVpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T05:15:04Z"
    mac: ENC[AES256_GCM,data:eB3/PbL6X7V6Qa9jl/CXp8halnJKIzitgDWwCsijze3Wq6fIJgx7W/OAyXR3ZZzSuz48pQRQ+R67mKqs49nGfWcT7orL5MLbbCnhI634WE/XnT9oZaEGu/y6AJ43CPBO0q8M5ILoIM0IcA3LLDcds2LXJSAsg+MytoHWzAXLrwA=,iv:E/1Ewf9gE3BePl7ApW+ziyNW4rbBoFFJMDXioPq7PJ0=,tag:A/BeK22/9Zddp9TaV9oixg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
