apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-secret
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:WNRhPRG8pg==,iv:pa1Qu6TVH/fMxI4cnAYLu+tJDxbeqNpgdFrUqEdoJXs=,tag:JavZPO3JoApGIHiyw7et5w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:TqoscJPY3w==,iv:GV2gVBX/2VH0HgHFqPC6pHO7OqIQrDmjCoQJEJpdBek=,tag:+Loot/NF2A71XUD/8rq0XA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/dVI05I+hXNvY3KahQmwaGvo48RFOg==,iv:rWCUxZxCple2ylDsecWu2r6GmPiS56n2C1LMrjtAt0Q=,tag:V+0aqW0xUWS95wl4m73doQ==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreGd5NHY4QWhEbXZpRWIw
            ekM5bGhOV1hFTHhhMVE3by9iend4MDcyM0JnCjEzSjRNL2FiQXNHak1vRUxCWGda
            MVQ3ZWh2V1FnK3c4QVRFS0VuU29Pb00KLS0tIFlWWEJpditnaUtOOEhwSGR4amVX
            clR6Tm9OUkh2Mk9zanQ3alFBeURCQ3MKlVfZPKl4reLSDUpsMogckWkwTeoeUVt0
            YeoWBAWUmIkgRFK52hgSejmMb5TPOGW4pgtfxxipY0QlG5kK3Hqe0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T04:50:08Z"
    mac: ENC[AES256_GCM,data:EUq8Ds7nuE0lY7eKegXd2/l6V9WTn6Chal7Vj/iyYSHkT9mP8JVOZlLtrwUD0Ek97QzecOCGUy+mrKDynBeILeDBcs4QNrOHazvLqwEu7//KvjhWt7yyaWYXGDa4LINqCMAWgQVLRSVkvUqsZK//z+AKrRU/UogTJXhz+SkQcKQ=,iv:yrc0YLkPvLGOAf53wYR0euNFJtlyQNZ+zzyZQGjT1JU=,tag:sKKhO0tlI35w6xo0ODpIVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
type: Opaque
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:1EOi2XrqG7gBzsl3omvMo8jaXl9tM27xTHtPN2nOsqI=,iv:z0F4vbuqWqvKi4bFMqVM3Yd1k7z4Sbmm0m0kO4BnBtA=,tag:Bk6AlW6tGsfj9Nek7aWaWg==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreGd5NHY4QWhEbXZpRWIw
            ekM5bGhOV1hFTHhhMVE3by9iend4MDcyM0JnCjEzSjRNL2FiQXNHak1vRUxCWGda
            MVQ3ZWh2V1FnK3c4QVRFS0VuU29Pb00KLS0tIFlWWEJpditnaUtOOEhwSGR4amVX
            clR6Tm9OUkh2Mk9zanQ3alFBeURCQ3MKlVfZPKl4reLSDUpsMogckWkwTeoeUVt0
            YeoWBAWUmIkgRFK52hgSejmMb5TPOGW4pgtfxxipY0QlG5kK3Hqe0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T04:50:08Z"
    mac: ENC[AES256_GCM,data:EUq8Ds7nuE0lY7eKegXd2/l6V9WTn6Chal7Vj/iyYSHkT9mP8JVOZlLtrwUD0Ek97QzecOCGUy+mrKDynBeILeDBcs4QNrOHazvLqwEu7//KvjhWt7yyaWYXGDa4LINqCMAWgQVLRSVkvUqsZK//z+AKrRU/UogTJXhz+SkQcKQ=,iv:yrc0YLkPvLGOAf53wYR0euNFJtlyQNZ+zzyZQGjT1JU=,tag:sKKhO0tlI35w6xo0ODpIVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:yT2VJPp7XGJKMouk9QZY9rjG5eWX7CK8E2MqnqIDgC2oHZZTcYVPmj15444LB5LDLL/G4KROJGCDb0E+lwJHABtb5f7pxkjCytKSR+GCXsJQtyX9xIozHmfVPmYh4FmmvECjFMSUAZBTEzdOWle+nZlUW4CCycGp9kVj2eVdcs2r1zSSDETZGeuQnDSnC+EBESMxidQYfusT8d0r/adWBB9602dVqHcI1+Dg//X0H+A=,iv:jnieHRrxP7NDGllCuSZiuVLG7aYRK6zN3l/n0iTv/1w=,tag:MiW2wBOswWvTwk9yf//Qpw==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreGd5NHY4QWhEbXZpRWIw
            ekM5bGhOV1hFTHhhMVE3by9iend4MDcyM0JnCjEzSjRNL2FiQXNHak1vRUxCWGda
            MVQ3ZWh2V1FnK3c4QVRFS0VuU29Pb00KLS0tIFlWWEJpditnaUtOOEhwSGR4amVX
            clR6Tm9OUkh2Mk9zanQ3alFBeURCQ3MKlVfZPKl4reLSDUpsMogckWkwTeoeUVt0
            YeoWBAWUmIkgRFK52hgSejmMb5TPOGW4pgtfxxipY0QlG5kK3Hqe0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T04:50:08Z"
    mac: ENC[AES256_GCM,data:EUq8Ds7nuE0lY7eKegXd2/l6V9WTn6Chal7Vj/iyYSHkT9mP8JVOZlLtrwUD0Ek97QzecOCGUy+mrKDynBeILeDBcs4QNrOHazvLqwEu7//KvjhWt7yyaWYXGDa4LINqCMAWgQVLRSVkvUqsZK//z+AKrRU/UogTJXhz+SkQcKQ=,iv:yrc0YLkPvLGOAf53wYR0euNFJtlyQNZ+zzyZQGjT1JU=,tag:sKKhO0tlI35w6xo0ODpIVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
