apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:aPFZvlU+sA==,iv:82o+NC2g6OwEQwmtNQX16+NbDDrElM/73TTgWlfOw/A=,tag:DWSemgCl42DiQ7V2hgRnhQ==,type:str]
    password: ENC[AES256_GCM,data:Q5X7rmmfhnb8kIf4XdTLRxOgvz5gY5PMQS6bbep6q0EtutaIg/QpT1TkI/0=,iv:2IliaX2Bk8qB9BY+LAJBVaZiALFJxNkpQ2j9yzht44Y=,tag:WCKogTEAOp1gSm+Jle3FeQ==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RVEwTG9YdWRyank0RE9B
            NHkrcm4xTFZCdDNXci9MSFJXbDlnU24zN0FBCmZjdFIyZEN6djBkdEh5dmhVZG50
            QzBoekdlLzFvdXBQcmgxSnNQSzI4WkUKLS0tIEJmd25KTFFhVGRMQ2lmNlRwNFZi
            ZkYzU2xCTlgyeTN1eVRvZnl2aWUzeUkKFkDhSukckZ/kKBpsIfwqlzIK5nMGOnwj
            yaeAy3qQyZmW0zqKlFs8V6RPwilX5iW8JIwHwiK2/hsx152GiWfR8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T21:32:32Z"
    mac: ENC[AES256_GCM,data:Di1tbkyeZKe+IGhsoBKTdjFibXIzgPbcyK3GHnC4cslgkxQrhX/bzfzG571zyYHUK7xAForLRZk4uCs8NUKQaNeb6a7WMFH2wf6aPkyyyHjNTDfmQCewnVNVgy1dqXNf4FJAIoQ4bNoHN2X0ug2j9oYX17oyrRuWbh9F4HHhVtE=,iv:8vlu32mYeFDMWZjJaAMvjgPNHXcWpnStfZ7ihY+mzZQ=,tag:1K/IR6Q5yMDXcSYjnoe35g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: forgejo
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:2b687qdCixSFHGDIWxVaD4QdYh1ZWurwLI/r1/B8JQwfSLtTzIx9cniUwv2Zlv76,iv:mp0kw1lysVManh0jTJz7CQ0es/xJzrFCXdPuMwdOpJ4=,tag:wuHFbj/xN5qWSgmYnLDR1A==,type:str]
    secret-key: ENC[AES256_GCM,data:Xvb+r9Qind87J51ox0yVaJa7ep75w8PDO1tq9vYjzGg2bcwaNYxLfB6SvtAurqAcjpEu7JRnu+HrZMzfTWYF9g==,iv:XGZiZpBuSzqSO0QXmSnjbV99hK14Y5Qo+RB5/yfVO2c=,tag:PnlmfsJhoA5f6sozCp3Tjg==,type:str]
    internal-token: ENC[AES256_GCM,data:pG3TDufoGpiaNJW1IhUMeV2WA+YdA9D66vUkT1rtdgfw6xm9DoASyNIFQmGkU+6q+VuC1FzEFDBlqDkeVAB9+Q==,iv:/TsbtyD2BMtKnscEjJc94xxcSYjPtsPn4UaD7WPR8pQ=,tag:h25vKredQF0aC9DLGju01Q==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RVEwTG9YdWRyank0RE9B
            NHkrcm4xTFZCdDNXci9MSFJXbDlnU24zN0FBCmZjdFIyZEN6djBkdEh5dmhVZG50
            QzBoekdlLzFvdXBQcmgxSnNQSzI4WkUKLS0tIEJmd25KTFFhVGRMQ2lmNlRwNFZi
            ZkYzU2xCTlgyeTN1eVRvZnl2aWUzeUkKFkDhSukckZ/kKBpsIfwqlzIK5nMGOnwj
            yaeAy3qQyZmW0zqKlFs8V6RPwilX5iW8JIwHwiK2/hsx152GiWfR8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T21:32:32Z"
    mac: ENC[AES256_GCM,data:Di1tbkyeZKe+IGhsoBKTdjFibXIzgPbcyK3GHnC4cslgkxQrhX/bzfzG571zyYHUK7xAForLRZk4uCs8NUKQaNeb6a7WMFH2wf6aPkyyyHjNTDfmQCewnVNVgy1dqXNf4FJAIoQ4bNoHN2X0ug2j9oYX17oyrRuWbh9F4HHhVtE=,iv:8vlu32mYeFDMWZjJaAMvjgPNHXcWpnStfZ7ihY+mzZQ=,tag:1K/IR6Q5yMDXcSYjnoe35g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-cloudflared
    namespace: forgejo
type: Opaque
data:
    credentials.json: ENC[AES256_GCM,data:CzkeX8fXAqo2aJp1WlgKpSztG0CA6biVuB4zyZvZJm0IbPsS9Rn2CnWowPbRZuVX2yIHCTj4qJFSA5szLXBkT66RBcNtjpVnVO+r6nkWbUD9hyI4LntKEb+QE1AwEb/ComfLE77KdOQIEzvjqCD78q7+yEjnSCA2W6nLi0uQMrGNy1RXdwd5YAVAbT+ThTymOxeRUAYj3kFfC5vqIn+0CYoWCNA4F70q72EEh0wYZl4e2Febw9dSJ+s1favHND4YqhBAJEIBGZxAWsiIngmwILb8uRmPiVTTJ8v3rQMNKZnrAGEwPYNmECmX8h8=,iv:O4T2yPAcZfVw3OajJn8SD+/BqXawlzmeKSZuZtJ+LVI=,tag:S3o2Oo7hf8TRAi4iSUSqNQ==,type:str]
    config.yaml: ENC[AES256_GCM,data:hfnteRamZJ7GefrhMg0x6g/Q5gG0mSyD3FswypuHQXDFaZ3iu8U2lwj1QUouLFT9HTPWsJVHIqHdqctTPmuNAHORsInj9JKxP4YXtiGf2OBvkq8G+HFG+010auMtoPJ9IcXaqeyuqEcUN1CiJV/XRgMqxf21QjKHTbyB738ijJdXSicVN0txvolY0i1B3DF9ZYAL90FgRMxtJt+dPWbkV3WXfyBBa76TTxaeGxE9Mw8Z7O4AlsnCyclSaOe/b167y862dlwkhXWyXOevpH0BkSE6qe+poAoKy1wReTtTqkACpfkVR/i7UTP+/5WRsWgmc4LD9lgEO2zOadggj7zhRLsCIvT/Z3lxjJSAcUOrxGV8kh3x2LkSQ8X7Zc35uQGSC8dYLNFgGWELkpVckCMczMtl2Tb6BEt2bAdCPriDaE1GDQWa/vRb4Z3es2PrWI+lMTBD87Kmwk6FhVOdVpIhM+vk+5DGX0WNLL+eMpRazsudKpulR51k0e/fgKtnoLIeHwOeHcljKRb9lz45lKGtWriuzi4h63dztrDMhw9sCkY9emfI7SWsmP4IjH2j4hCKuq8dJq+szXDoi7hY4szhauJfwbqpPguB,iv:85A8KRAjJOlT6L5obwZUBQsWlR5hDW44AAU0xAM7ZNw=,tag:UP3jX6p5kv+heuMQQR6ohw==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RVEwTG9YdWRyank0RE9B
            NHkrcm4xTFZCdDNXci9MSFJXbDlnU24zN0FBCmZjdFIyZEN6djBkdEh5dmhVZG50
            QzBoekdlLzFvdXBQcmgxSnNQSzI4WkUKLS0tIEJmd25KTFFhVGRMQ2lmNlRwNFZi
            ZkYzU2xCTlgyeTN1eVRvZnl2aWUzeUkKFkDhSukckZ/kKBpsIfwqlzIK5nMGOnwj
            yaeAy3qQyZmW0zqKlFs8V6RPwilX5iW8JIwHwiK2/hsx152GiWfR8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T21:32:32Z"
    mac: ENC[AES256_GCM,data:Di1tbkyeZKe+IGhsoBKTdjFibXIzgPbcyK3GHnC4cslgkxQrhX/bzfzG571zyYHUK7xAForLRZk4uCs8NUKQaNeb6a7WMFH2wf6aPkyyyHjNTDfmQCewnVNVgy1dqXNf4FJAIoQ4bNoHN2X0ug2j9oYX17oyrRuWbh9F4HHhVtE=,iv:8vlu32mYeFDMWZjJaAMvjgPNHXcWpnStfZ7ihY+mzZQ=,tag:1K/IR6Q5yMDXcSYjnoe35g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
