apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
    namespace: obsidian-sync
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:1mGPxSdDcg==,iv:7H1B+lMUk/+p9tAnKi+X79qXhGEHvpDag2o+QTFIPrM=,tag:xD4sNay0UT6/LZAx6IN+0A==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:1nFblIdGRETocEabKERsrgQkydCfN/s=,iv:gj52kHqobDAZe4SVV8/8e57Wtc0RPeVIOutKC/rP7Tg=,tag:7hC3/s9XzGsDVwYbbdgPZw==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWDROZnNXT3BiUEMxaDly
            TXZMejliU21xRnV5aWpMQkpPQmVtSnFOWEhrCmcwNG5DaGZxbHB1WnZLcHJMOFBa
            VDNSQlpqN0F1UVplVERKSXNGUDVxSVUKLS0tIGU1R2Z6b0p4UE1nZ3hTUW94Y1VW
            eUlWOUhNVUlOZGl5N21TOEhEK0ttOFUK6/G1o9OUglXzO1rzjwkz7BTecrgKtf9s
            3M3s10vIQyQ3UydGarCoy7hHi+8N+fB7UNX00/+hUIzZSN/a0BQCNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:43:20Z"
    mac: ENC[AES256_GCM,data:LyYBK2Qq9UYbW5zQa1Z0aFuP1C/rJYt6noUdyb5vEdnhUNJoW3ye9a383W74u/RVrMyOCWzmsG7kjGw7HPRHQrnT6AjdZFROcRc0oc1cQuPykybQTxMvHbWeKQowkCeGbHciH0JiyXQj5SvedHw5ZdK3y7PyMKl5hhhg9z7agdo=,iv:rw8UaPW4cz2Py5/UPhGSjsA6HUtYY46zs5iASGX+yo8=,tag:02r7fTY9k5ys/+Jq8ta/kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials-obsidian
    namespace: obsidian-sync
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:8XR274hc4Z0eFmboaPBjHXgBX54QVTX0OiPeGgRCi163qWhadcmwSMF4kw0eIzIUqzq/p/NUqkuA4CiJSsks3WzrtW1U9uB8XvrdSB0Z5Bc/KZ+EfvsRW0sOtejN36bGp6Rd7EcNYguMLXDwJYpvQ+q7/rXBLxIcaoHIs+YnL0RtDQdMVoe59K7Efv7CGMHTJy7xNfx7Tm/g4gj2lQtR+W9eKdAjnqDIwUmJpdlD,iv:6Ap8iozif38fmsYrXAAkv8MsDWzKrnRh1UJ73TfwzmE=,tag:grS/9eAEs3RhlwN1wRu8iA==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWDROZnNXT3BiUEMxaDly
            TXZMejliU21xRnV5aWpMQkpPQmVtSnFOWEhrCmcwNG5DaGZxbHB1WnZLcHJMOFBa
            VDNSQlpqN0F1UVplVERKSXNGUDVxSVUKLS0tIGU1R2Z6b0p4UE1nZ3hTUW94Y1VW
            eUlWOUhNVUlOZGl5N21TOEhEK0ttOFUK6/G1o9OUglXzO1rzjwkz7BTecrgKtf9s
            3M3s10vIQyQ3UydGarCoy7hHi+8N+fB7UNX00/+hUIzZSN/a0BQCNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:43:20Z"
    mac: ENC[AES256_GCM,data:LyYBK2Qq9UYbW5zQa1Z0aFuP1C/rJYt6noUdyb5vEdnhUNJoW3ye9a383W74u/RVrMyOCWzmsG7kjGw7HPRHQrnT6AjdZFROcRc0oc1cQuPykybQTxMvHbWeKQowkCeGbHciH0JiyXQj5SvedHw5ZdK3y7PyMKl5hhhg9z7agdo=,iv:rw8UaPW4cz2Py5/UPhGSjsA6HUtYY46zs5iASGX+yo8=,tag:02r7fTY9k5ys/+Jq8ta/kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
