apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: headlamp
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:6YiBmpXo+eSlmj4h/EuAwcH3gkBWZwu/rK11bBQ/qfb3ndgQUS+Lz4qizSdVCQo1usJss8yfyWRbbrerIQNIMwdJuNaHwvr/xQxgvDF+Z6SvIYB4W+bQjhQ3pZ2CLQtLiFNXFkqz/mqH6H61WPS25uOfqwbVREBQrohZzcUAKCVgvL2U/tFuL2ljJn7bYXuLoJZwOifeIGkSY/7AWIoGQjb9Cap9Newih4URTmFQy5KRdtv35IZod4iQvyMfYd8k,iv:9k7UjytmcEOZMjlpREjg2HsVBj8ieMsd5WlVUKheru8=,tag:nYPn97x27Dub8auvKQQCWw==,type:str]
    config.yaml: ENC[AES256_GCM,data:8yIRMt1KoPZGtrNbtsaHY+0iEiKZ6YoTg3ry51c2ZJFqSnh7xtgPtvVPzO35+NOxdX1Vlyi1K9T2zjRSvimYFz9m49ai2ngc+tstXqGKH/0Ongsn+Fx0DBjt8is7dbiEJrwEt+ao0cG8siqp3/VV+OWsJ1kXm/6qH8AZdqbVT+dA1W4nNI6unESC8jxXbwaUtEbJppfjraTTXN7Xxd9/e42C9zVOj6dzceuB1IJx+Hefb+AuOLnQcvDl6cJahIi9V/8Fw96DO4AohE12oUy4KqUkgAlB49rLSlL8WITVxYitdXe8Ow/Fes8O/0l6XyDC6gSJLPau2YIVxBUViZykiJZqivOz9uF/19ePnV7CFqRFunSJxOMCaY/fcxDgSIS/pNHTlnXWTq3aOEfow0D2AD0ZwxrOsLufpK7wV/mVnEViiL9xkliuroNXQWhP3253Ip79hbZJovbf8BsGMTmF6H7SS3dEHIE4,iv:H+YQKFdEIaFrwMkfdm6mH6Qc7F5+3K19Z+u9LDpoD/M=,tag:nAsxjlftjEqO/ZwDTIrSyQ==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdllnNUFNZndYamMyRm1t
            clJrUVdodHJkZ0FYbUhtZXI5a0Juako4UDNRCjY4RUdiU2tRdmNFQWZrMnhtOWwr
            dDZQem1Kd2xxNzRVWGNnRTJVeWx6T1UKLS0tIDJyRzhRUGNOTms0NU02NVp1Ymp0
            M00vL25GK0FVVWpuNXRaV1VsT0wwcGcK6GULmkxynEaaF6ZYm8Zcd5NnZ0eJpQqv
            bgEFXN+lEcSuD/AqQQjWYQcmfcrIWCX6hr12+rvMHxNKqeVnC7VLIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T01:13:26Z"
    mac: ENC[AES256_GCM,data:vJK/OPOvepjqRHBsOxXz7R28hgzmLa7/sSr76Ip/Jlxg1+qg7xqqIpv6pHFzwrQYEzGzv6SufRp13Qemo5cgDuKzw5cdmYzevqtNhX5yy+X2DjF8R6U1QwvamtGI0Z0pCP0IPzIVz/1JHPFd8v59WO4QBjxvdopd/sMNCtMYcLg=,iv:G02g+4zvjwSTgtn2k/UY+XZ7lbvqepAu9he/Llfp9B8=,tag:sVLUD5R71WdnXg5wBcy1kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
