apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: docmost
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubethink
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --maxmemory-policy
            - noeviction
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
