apiVersion: v1
kind: Secret
metadata:
    name: velero-minio-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:wMaP8CfRpzd2G16W1cMnVJ/00qEpJCpBL0HMpqkFgYtNxVRTtyxmGzodR5kFz41LiVepJvDpj5VY6yZw1lbYMvBefJ0MYvq6cFnKUfIMBw==,iv:dnYpcBCJki4T0lRFyh6S+i93IndQI1ILIe+PwnnFPHU=,tag:Scb3wgtY4bMs55zy+TTVnA==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cWtKL3RDb2JVTEVVbkhJ
            YnBsZ2FITHRMR3o3MkZIQndEWnIxNUxUdVN3CmhTSG9SbURDcWJzMGQ3Q05CaGkv
            SjR3MjRXZmpnNU1IdWJSSFE3bVU5MjgKLS0tIDJSc3JEc1dMdW03cWo0QkptMllM
            N205eDAyRXNKeFNKUkhVaXd6N0k4RE0K71xc7mYRymTf0lD4ZnOLZvmN8ekehfID
            bgF2XAQmK9MC8hdDK2UbiudKLUr07Q+04PwoPp32Bgnzf/vUjseOPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T05:58:54Z"
    mac: ENC[AES256_GCM,data:qCBN9JetJZkPYY3tTmYPmbQBh1UxEHB8fjUoazH/KJmMYZOu04PwyY4V8lX1EB3vKm0vfgudvEIgPClgwy8tTEPldQxXYE9In+pdYbOhdOXkhtP9xTWCjom1jWN0YlK7NcmeAv692Ui8sfjl/LFCRza1ccjWConqA/2BKtTaJ6Y=,iv:XrMJRVvfiVhuEJRN3RJk2Ji3MD4dz+vQFjlW5p4ded4=,tag:liFYvYfUbl4yO13Omy4i+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
