apiVersion: v1
kind: Secret
metadata:
    name: velero-minio-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:ZgOuI71kC6dMndKrSNB0Epxxrola0s9p19Jk02X0+9TkLKQTnTS+Yxn8nccTT6dSIbCiKG6f+Lo52yaXxI1TjgVouLkj7gABgkeOq2xyOA==,iv:Z6sMYd562wdX/O/7mpTa7cC6SZ6FjF8aYkkoEekBwNs=,tag:UwOL73H/RpTjf3gJXEzP4w==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZmdLQWVXcVV2SnNUeWlO
            MUpEMHo2YnlxZVpWSE5aT3ZUNm91U1lkSkUwCkVhLytNeUhVd2poT3Nqc0E1Wmh6
            NW1xdFRvSm9zRDZqVHFzNmtIMHpvSG8KLS0tIDg5S1VCZTU4ODM0RlVueDNLM1RH
            WXVvRDEwZlh6alBwRzZUenpRQVN4TnMKw8wjf7esLe3BRURYKuGjLB7kBWPVolx0
            hHTPGJqclbfBCenO31Fk59T70FbPMbR2ejDDfR6p0kyrHVcJdlVnvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T06:06:45Z"
    mac: ENC[AES256_GCM,data:FL/FAqrtfnRv1dpvLBo9DUDrthxlPGlixaiH67Y60HfD6B+79zD9xBLohjrioQuIxClY95m7IJQbkQaqvIJ98Z4GJ9Mv3BQARym7eeisgvKFS5ffOARuxw1Mm+UewJSAxHVIbbQ5HJv12ZmLxvuFhT1/yYVwmceSmm8z1mwqo7M=,iv:PWOnF159hsgtjQ99SJQM3GGgfkwIBEuSyLmlfUTGMxo=,tag:bHLPQSKGbZq9GoESquz3Uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
