apiVersion: v1
kind: Secret
metadata:
    name: velero-minio-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:fK1w+W3ZEol/FeZXimjb+6BLWedRjMPUWY14yqxkRaOpF/NCnZ5VJjThu4SNxXNSA0B0VcymA35DEttWSPg2tjtQCYz8yw==,iv:hXaYwIwIG9lM8Vwx/pNKP7omCJbZ7Ac9Cjq7J1mHscA=,tag:uhgpbk2fBlrHLz66hOJfog==,type:str]
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSk1DUkpwcUFkaTRqTU5u
            Zkc1c040SHZycXhxS3lKYXdpWmlHQkpLMXlNCjNzTUlSUUkzY2J1WlBKWVRjV3pQ
            QnZVa2lyR0pzdk5TMVA1bUFCTFdqS2MKLS0tIGZhMGMvUTFNb0lLQmcxQXFMTitS
            a1lLYXhzRG9DM1pvYU1BTDRVYm04TkkKhEJvPdGFPi+z2+L4hodMj06NAVPx3mJ7
            4fcNpSQBivFEIjrAOBQzf7O1l8c8xaLO7o5EMNPTMxvdTCkE1Ly6RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T05:13:32Z"
    mac: ENC[AES256_GCM,data:WWKR7yqBUbOCeOQy28M/PBeSz1iWGdyR9OjuIuACf/ws9VZGgnfzqj58KWeETbRJA7XIfVQ3zzIkJvTvfsd5cuVgoJc3N1VQCOrtSE1jHB74Qz3fqtaBVeK6CCQutDD8nJ13O5tJi91Ovcwe+Ps5XCNxGKY8HrS3OgIII3wncmY=,iv:h8McKHe5qSpycCVefR86xgvSujbcHsLuhubVgRAYQ/c=,tag:cUq6FerB97qmTpWNdR5fnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
