apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:TkxOIn/AxMk9QpbUsVHNDj81V4l9ulDCneR+n6gBS5UYxMzdj8C4WVG3GtuRbHHrMjrt0xGW83M=,iv:W+OEV/UeceB4ksivp+WxbPkIpyUIGy7XyTZlTT41qV0=,tag:2I/1lq7nIOAa+3tz0zehpA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age1esq3qzaqeuwrfzu8fx89u9k8dl3uvmse460l29kt28yj8vefn9wstkgdn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNG14Q3ltVjhNMk5xM2Vm
            bzVvOWZnc1hDSCtrL3RmSEVuZmhFemxLem44CkMrcDV0THZPemxmajBJWnF5bndw
            MjBIdlYyWFg0KzhaOW5tcVo4U3N1SGsKLS0tIGk3Wkh6QTBOb2VVSmdmNHF4NUNC
            U05UNExqVGtjRHIydks1Sm05ZUc4SlkKvJTI9BMmcOoDmctzgZp3d9yNuNwgqu+T
            iGaYd2zNBaH3UurbutOuOtplknNbbLsEBc3tC+n5QK3E3K0Tg/V/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T04:18:04Z"
    mac: ENC[AES256_GCM,data:Sn2r4MDj0cKj3A5ZcQkJiUacWH9iTUzhrpxzcTK/CNQ5NZiyJlp/2DA7xVPRNGUlEXNUhmdvK+dXLvqdr5sTp5DczTqPXYcVGjJJXemX0cxHK22Y9DZlUB7xZMxpBdx/umS19uNGy0vgrvsnpyV7e3Mu3ueHmeNEkIbSyB2+9+0=,iv:2AgrjoWUHJIAQS7YTFHjyT8MuPnr17HVdlRfd7BWUJk=,tag:8Him+aK3lLs9rIaWqBhm7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
